const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const assert=require('node:assert/strict');
const source=fs.readFileSync(path.resolve(__dirname,'../frontend/source/ui-domain.js'),'utf8');
const context={window:{}};vm.createContext(context);vm.runInContext(source,context);
const ui=context.window.GpoUiDomain;
const base={result:{state:'PUBLISHED',gpoPublished:true,linkVerified:true,verification:{replicationConverged:true},effectiveStatus:'VERIFIED_ON_SAMPLE'}};
assert.equal(ui.classify(base).compliant,true,'fully verified publication must be compliant');
assert.equal(ui.classify({result:{...base.result,effectiveStatus:'ENDPOINT_VERIFICATION_PENDING'}}).compliant,false,'publication alone must not be reported as compliant');
assert.equal(ui.classify({result:{...base.result,verification:{replicationConverged:false}}}).replication,'pending');
assert.equal(ui.classify({result:{...base.result,state:'REVIEW_REQUIRED'}}).attention,true);
assert.equal(ui.classify({result:{...base.result,state:'NO_CHANGE',gpoPublished:false}}).compliant,false,'no-change label must not override failed publication read-back');
assert.equal(ui.workflowStep({run:base}),6);
assert.equal(ui.workflowStep({plan:{},approvalReviewed:false}),3);
assert.equal(ui.workflowStep({plan:{},approvalReviewed:true}),4);
assert.equal(ui.impact({title:'password policy',operationalImpact:'LOW'}).name,'Low','impact must use server metadata, not title keywords');
assert.equal(ui.impact({operationalImpact:'HIGH',impactReason:'Server reason'}).copy,'Server reason');
console.log('PASS: UI domain truth model separates publication, replication, effective verification and workflow state.');
