/* Deterministic offline CSS build. Preserves selector order and specificity. */
const fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'../frontend/source'),dir=path.join(root,'styles');
const files=['tokens.css','settings.css','layout.css','command.css','console.css','product.css','screens.css','components.css'];
function blocks(css){let result=[],start=0,depth=0,quote='',comment=false;for(let i=0;i<css.length;i++){const c=css[i],next=css[i+1];if(comment){if(c==='*'&&next==='/'){comment=false;i++;}continue;}if(quote){if(c==='\\'){i++;continue;}if(c===quote)quote='';continue;}if(c==='/'&&next==='*'){comment=true;i++;continue;}if(c==='"'||c==="'"){quote=c;continue;}if(c==='{')depth++;if(c==='}') {depth--;if(depth===0){result.push(css.slice(start,i+1).trim());start=i+1;}}}if(depth!==0||quote||comment)throw Error('Unbalanced CSS');if(css.slice(start).trim())result.push(css.slice(start).trim());return result;}
const chunks=files.flatMap(name=>blocks(fs.readFileSync(path.join(dir,name),'utf8')));
// Exact duplicated blocks can safely retain the last occurrence. No reordering,
// shorthand expansion, arbitrary selector merging, or !important stripping.
const seen=new Set(),dedup=[];for(let i=chunks.length-1;i>=0;i--){const key=chunks[i].replace(/\/\*[\s\S]*?\*\//g,'').trim();if(!seen.has(key)){seen.add(key);dedup.push(chunks[i]);}}
const output='/* Generated by scripts/Build-Styles.cjs. Edit styles/ component sources. */\n'+dedup.reverse().join('\n')+'\n';
const target=path.join(root,'app.css');
if(process.argv.includes('--check')){if(!fs.existsSync(target)||fs.readFileSync(target,'utf8')!==output)throw Error('app.css is stale');}else fs.writeFileSync(target,output);
console.log(`Styles: ${files.length} component sources → app.css; ${chunks.length-dedup.length} exact duplicate blocks removed.`);
